/**
 * Application registry storing metadata about available phone apps.
 *
 * @typedef {Object} AppDefinition
 * @property {string} id Unique string identifier.
 * @property {string} name Display name for the app.
 * @property {string} icon Lucide icon component name.
 * @property {'apps'|'tools'|'info'} category Category grouping.
 * @property {boolean} isLocked Whether the app is locked at start.
 * @property {string[]} unlockRequirements IDs of prerequisite apps.
 * @property {string} description Short description of the app.
 * @property {string} launchScreen Component name to render when launched.
 */

/**
 * A registry of all app definitions keyed by their id.
 * @type {Record<string, AppDefinition>}
 */
export const appRegistry = {
  communicator: {
    id: 'communicator',
    name: 'Communicator',
    icon: 'MessageCircle',
    category: 'apps',
    isLocked: false,
    unlockRequirements: [],
    description: 'Send and receive encrypted transmissions.',
    launchScreen: 'CommunicatorScreen',
  },
  map: {
    id: 'map',
    name: 'Map',
    icon: 'Map',
    category: 'apps',
    isLocked: true,
    unlockRequirements: ['communicator'],
    description: 'Displays known territory and points of interest.',
    launchScreen: 'MapScreen',
  },
  droneControl: {
    id: 'droneControl',
    name: 'Drone Control',
    icon: 'Drone',
    category: 'apps',
    isLocked: true,
    unlockRequirements: ['communicator', 'map'],
    description: 'Operate reconnaissance drones remotely.',
    launchScreen: 'DroneScreen',
  },

  scanner: {
    id: 'scanner',
    name: 'Scanner',
    icon: 'ScanSearch',
    category: 'tools',
    isLocked: false,
    unlockRequirements: [],
    description: 'Scan surroundings for signals and anomalies.',
    launchScreen: 'ScannerScreen',
  },
  terminal: {
    id: 'terminal',
    name: 'Terminal',
    icon: 'Terminal',
    category: 'tools',
    isLocked: false,
    unlockRequirements: [],
    description: 'Access system command line utilities.',
    launchScreen: 'TerminalScreen',
  },
  decryptor: {
    id: 'decryptor',
    name: 'Decryptor',
    icon: 'KeyRound',
    category: 'tools',
    isLocked: true,
    unlockRequirements: [],
    description: 'Break encrypted archives and messages. Useful for cipher challenges.',
    launchScreen: 'DecryptorScreen',
  },
  scriptBuilder: {
    id: 'scriptBuilder',
    name: 'Script Builder',
    icon: 'ClipboardList',
    category: 'tools',
    isLocked: true,
    unlockRequirements: [],
    description: 'Visually assemble and test command scripts. Helps with script challenges.',
    launchScreen: 'ScriptBuilderScreen',
  },

  handbook: {
    id: 'handbook',
    name: 'Survival Handbook',
    icon: 'Book',
    category: 'info',
    isLocked: false,
    unlockRequirements: [],
    description: 'Reference guide on wasteland survival tactics.',
    launchScreen: 'HandbookScreen',
  },
  worldStats: {
    id: 'worldStats',
    name: 'World Stats',
    icon: 'BarChart2',
    category: 'info',
    isLocked: true,
    unlockRequirements: ['handbook'],
    description: 'View current radiation and weather levels.',
    launchScreen: 'StatsScreen',
  },
  signalLog: {
    id: 'signalLog',
    name: 'Signal Log',
    icon: 'Activity',
    category: 'info',
    isLocked: true,
    unlockRequirements: ['handbook'],
    description: 'Archive of intercepted radio chatter.',
    launchScreen: 'LogScreen',
  },
  trophyRoom: {
    id: 'trophyRoom',
    name: 'Trophy Room',
    icon: 'Award',
    category: 'info',
    isLocked: false,
    unlockRequirements: [],
    description: 'View earned achievements.',
    launchScreen: 'TrophyRoomScreen',
  },
  securityTraining: {
    id: 'securityTraining',
    name: 'Security Training',
    icon: 'ShieldCheck',
    category: 'apps',
    isLocked: false,
    unlockRequirements: [],
    description: 'Interactive security quiz challenges.',
    launchScreen: 'SecurityTrainingApp',
  },
  networkScanner: {
    id: 'networkScanner',
    name: 'Network Scanner',
    icon: 'Radar',
    category: 'tools',
    isLocked: true,
    unlockRequirements: [],
    description: 'Detect nearby network devices. Aids network challenges.',
    launchScreen: 'NetworkScanner',
  },
  portScanner: {
    id: 'portScanner',
    name: 'Port Scanner',
    icon: 'Server',
    category: 'tools',
    isLocked: true,
    unlockRequirements: [],
    description: 'Scan ports on a target system. Useful for infiltration tasks.',
    launchScreen: 'PortScanner',
  },
  firewall: {
    id: 'firewall',
    name: 'Firewall',
    icon: 'Shield',
    category: 'tools',
    isLocked: true,
    unlockRequirements: [],
    description: 'Configure firewall rules. Critical for defense challenges.',
    launchScreen: 'FirewallApp',
  },
  leaderboard: {
    id: 'leaderboard',
    name: 'Leaderboard',
    icon: 'List',
    category: 'info',
    isLocked: false,
    unlockRequirements: [],
    description: 'View local high scores.',
    launchScreen: 'LeaderboardScreen',
  },
  settings: {
    id: 'settings',
    name: 'Settings',
    icon: 'Settings',
    category: 'info',
    isLocked: false,
    unlockRequirements: [],
    description: 'Configure audio, display, and gameplay options.',
    launchScreen: 'SettingsScreen',
  },
  ddosSimulator: {
    id: 'ddosSimulator',
    name: 'DDoS Simulator',
    icon: 'Activity',
    category: 'tools',
    isLocked: true,
    unlockRequirements: [],
    description: 'Visualize distributed denial of service attacks. Training for defense levels.',
    launchScreen: 'DDoSSimulator',
  },
  packetAnalyzer: {
    id: 'packetAnalyzer',
    name: 'Packet Analyzer',
    icon: 'PackageSearch',
    category: 'tools',
    isLocked: true,
    unlockRequirements: [],
    description: 'Capture and inspect network packets. Helpful in network analysis challenges.',
    launchScreen: 'PacketAnalyzer',
  },
  chemicalDatabase: {
    id: 'chemicalDatabase',
    name: 'Chemical DB',
    icon: 'Database',
    category: 'tools',
    isLocked: true,
    unlockRequirements: [],
    description: 'Practice SQL queries on survival compounds. Supports database puzzles.',
    launchScreen: 'ChemicalDatabase',
  },
  radiationMonitor: {
    id: 'radiationMonitor',
    name: 'Radiation Monitor',
    icon: 'Radiation',
    category: 'tools',
    isLocked: true,
    unlockRequirements: [],
    description: 'Detect environmental radiation levels. Helps radiation challenges.',
    launchScreen: 'RadiationMonitor',
  },
  emergencyKeypad: {
    id: 'emergencyKeypad',
    name: 'Emergency Keypad',
    icon: 'Keyboard',
    category: 'tools',
    isLocked: true,
    unlockRequirements: [],
    description: 'Enter bunker access codes. Used in sequence challenges.',
    launchScreen: 'EmergencyKeypad',
  },
};
