name: Deploy React App
permissions:
  id-token: write
  contents: read
  pages: write
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.x'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the React app
      - name: Build
        run: npm run build
        env:
          CI: false

      # Upload the build directory as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: build # Adjust 'build' if your output folder is different

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
